//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transport_2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class transportEntityContext : DbContext
    {
        public transportEntityContext()
            : base("name=transportEntityContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> address { get; set; }
        public virtual DbSet<courier> courier { get; set; }
        public virtual DbSet<fos_user> fos_user { get; set; }
        public virtual DbSet<package> package { get; set; }
        public virtual DbSet<package_route> package_route { get; set; }
        public virtual DbSet<package_status> package_status { get; set; }
        public virtual DbSet<package_tag> package_tag { get; set; }
        public virtual DbSet<package_transaction> package_transaction { get; set; }
        public virtual DbSet<position> position { get; set; }
        public virtual DbSet<tag> tag { get; set; }
        public virtual DbSet<transfer_status> transfer_status { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
    }
}
