//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transport_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public package()
        {
            this.package_tag = new HashSet<package_tag>();
            this.package_transaction = new HashSet<package_transaction>();
        }
    
        public int id { get; set; }
        public Nullable<int> start_address { get; set; }
        public Nullable<int> target_address { get; set; }
        public Nullable<int> current_position { get; set; }
        public Nullable<int> package_status { get; set; }
        public Nullable<int> transfer_status { get; set; }
        public Nullable<int> courier { get; set; }
        public Nullable<int> handler { get; set; }
        public int width { get; set; }
        public Nullable<System.DateTime> request_date { get; set; }
        public System.DateTime delivered_date { get; set; }
        public Nullable<int> tag { get; set; }
        public int height { get; set; }
        public int length { get; set; }
        public Nullable<int> owner { get; set; }
    
        public virtual address address { get; set; }
        public virtual address address1 { get; set; }
        public virtual address address2 { get; set; }
        public virtual courier courier1 { get; set; }
        public virtual fos_user fos_user { get; set; }
        public virtual fos_user fos_user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<package_tag> package_tag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<package_transaction> package_transaction { get; set; }
        public virtual transfer_status transfer_status1 { get; set; }
        public virtual tag tag1 { get; set; }
        public virtual package_status package_status1 { get; set; }
    }
}
