//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transport_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public package_transaction()
        {
            this.package_route = new HashSet<package_route>();
        }
    
        public int id { get; set; }
        public Nullable<int> package { get; set; }
        public Nullable<int> package_status { get; set; }
        public Nullable<int> transfer_status { get; set; }
        public Nullable<int> courier { get; set; }
        public System.DateTime transaction_date { get; set; }
    
        public virtual courier courier1 { get; set; }
        public virtual package package1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<package_route> package_route { get; set; }
        public virtual package_status package_status1 { get; set; }
        public virtual transfer_status transfer_status1 { get; set; }
    }
}
