//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transport_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_tag
    {
        public int id { get; set; }
        public Nullable<int> package { get; set; }
        public Nullable<int> tag { get; set; }
    
        public virtual package package1 { get; set; }
        public virtual tag tag1 { get; set; }
    }
}
